UcbWeb/Controllers/ConfirmationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UcbWeb.ViewModels;
using UcbWeb.UcbService;
using UcbWeb.Helpers;
using UcbWeb.Models;

namespace UcbWeb.Controllers
{
    public class ConfirmationController : BaseController
    {
        
         // Dependency Injection enabled constructors

        private IUcbService UcbService;
        public ConfirmationController()
            : this(new UcbServiceClient(), new SessionManager(), new CacheManager())
        {
        }

        public ConfirmationController(IUcbService UcbService, ISessionManager sessionManager, ICacheManager cacheManager)
            : base(sessionManager, cacheManager)
        {
            this.UcbService = UcbService;
        }

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Confirmation/
        public ActionResult EmailConfirmation(FormCollection collection)
        {
            EmailVM model = new EmailVM();

            model = sessionManager.EmailDetails;

            return View(model);
        }

        public ActionResult LineManagerUpdateConfirmation(FormCollection collection)
        {
            IncidentVM model = new IncidentVM();

            model.IncidentItem = sessionManager.CurrentIncident;
            model.NominatedManager = sessionManager.NominatedManager;
            model.NominatedManagerEmailAddress = sessionManager.NominatedManagerEmailAddress;
            return View(model);
        }

        public ActionResult LineManagerCompletedActionConfirmation(FormCollection collection)
        {
            IncidentVM model = new IncidentVM();

            model.IncidentItem = sessionManager.CurrentIncident;
            model.NominatedManager = sessionManager.NominatedManager;
            model.NominatedManagerEmailAddress = sessionManager.NominatedManagerEmailAddress;
            return View(model);
        }


    }
}

UcbWeb/Views/Confirmation/EmailConfirmation.cshtml
@model UcbWeb.ViewModels.EmailVM
@{
    ViewBag.Title = Resources.INCIDENT_CREATION_CONFIRMATION;
}
<script type="text/javascript">
    /// <reference path="jquery-1.7.1.js" />
    /// <reference path="jquery-ui.js" />
    $(document).ready(function () {

        var isDirty = @(Model.IsViewDirty ? Html.Raw("true") : Html.Raw("false"));

        $(':input').change(function () {
            if (!isDirty) {
                isDirty = true;
            }
        });
		
		var $myDialogDelete = $('<div id=\'delete_dialog_fw\'></div>')
        .html('Are you sure you want to delete?<br/>Click OK to confirm.  Click Cancel to stop this action.')
        .dialog({
            autoOpen: false,
            modal: true,
            title: 'Confirmation Required',
            buttons: {
                "OK": function () {
                    $(this).dialog("close");
                    if ($('#IsDeleteConfirmed').val() == "True") {
                        var form = $('#mainForm')
                        var input = $("<input>").attr("type", "hidden").attr("name", "Edit::DeleteSystemParameter").val("");
                        form.append($(input));
                        $('#mainForm')[0].submit();
                        return true;
                    }
                }
                , "Cancel": function () {
                    $(this).dialog("close");
                    return false;
                }
            }

        });
		
		var $myDialogExit = $('<div id=\'exit_dialog_fw\'></div>')
        .html('Are you sure you want to exit?<br/>Click OK to confirm.  Click Cancel to stop this action.')
        .dialog({
            autoOpen: false,
            modal: true,
            title: 'Confirmation Required',
            buttons: {
                "OK": function () {
                    $(this).dialog("close");
                    if ($('#IsExitConfirmed').val() == "True") {
                        var form = $('#mainForm')
                        var input = $("<input>").attr("type", "hidden").attr("name", "Edit::ExitSystemParameter").val("");
                        form.append($(input));
                        $('#mainForm')[0].submit();
                        return true;
                    }
                }
                , "Cancel": function () {
                    $(this).dialog("close");
                    return false;
                }
            }

        });

        $('#mainForm').submit(function (e) {

            if ($('#mainForm').find('input[type="submit"]:focus').attr('name') == 'Edit::DeleteSystemParameter') {
                e.preventDefault();
                $('#IsDeleteConfirmed').val("True");
                var returnValue = $myDialogDelete.dialog('open');  //replace the div id with the id of the button/form
                return returnValue;
            }
            else if ($('#mainForm').find('input[type="submit"]:focus').attr('name') == 'Edit::ExitSystemParameter') {
                if (isDirty == true) {
                    e.preventDefault();
                    $('#IsExitConfirmed').val("True");
                    var returnValue = $myDialogExit.dialog('open');  //replace the div id with the id of the button/form
                    return returnValue;
                }
                else {
                    $('#IsExitConfirmed').val("True");
                    return true;
                }
            }
            else {
                return true;
            }
        });
	});
	
</script>
@using (Html.BeginForm("EmailConfirmation", "Confirmation", FormMethod.Post, new { @id = "mainForm" }))
{
    
    <div class='message'>@Model.Message</div>
    @Html.ValidationSummary(false, @Resources.ERROR_SUMMARY_TITLE, new { id = "validation_errors" })
    
    <div class="full-width clearfix">
        <fieldset class="ui-widget ui-widget-content ui-corner-all TextAlignCentre">
            <legend>@Resources.INCIDENT_EMAIL_SENT</legend>
            @if (String.IsNullOrEmpty(Model.LineManagerEmailAddress))
            { 
                <div class="full-width clearfix">
                    An email has <b>not</b> been sent to your Line Manager
                    @Model.IncidentItem.ManagerFirstName
                    @Model.IncidentItem.ManagerLastName for their attention. An email <b>has</b> been sent to your 
                    Nominated Manager @Model.NominatedManager (@Model.NominatedManagerEmailAddress) for information.
                </div>
            }
            else
            {
                <div class="full-width clearfix">
                    The incident has been reported to your Line Manager @Model.ManagerFirstName
                    @Model.ManagerLastName (@Model.LineManagerEmailAddress) for their attention.
                </div>
            }
            <div class="full-width clearfix">
                Your incident will now be processed.
            </div>
            <div class="full-width clearfix">
                If you would like to know the progress of this report please contact your Nominated
                Manager @Model.NominatedManager (@Model.NominatedManagerEmailAddress) quoting Incident
                Reference no: @Model.IncidentItem.IncidentID.
            </div>
            <div>
                Please close this window.
            </div>
        </fieldset>
    </div>
}

UcbWeb/Views/Confirmation/LineManagerCompletedActionConfirmation.cshtml
@model UcbWeb.ViewModels.IncidentVM
@{
    ViewBag.Title = Resources.INCIDENT_LINEMANAGERACTIONSCOMPLETE_CONFIRMATION;
}
<script type="text/javascript">
    /// <reference path="jquery-1.7.1.js" />
    /// <reference path="jquery-ui.js" />
    $(document).ready(function () {

        var isDirty = @(Model.IsViewDirty ? Html.Raw("true") : Html.Raw("false"));

        $(':input').change(function () {
            if (!isDirty) {
                isDirty = true;
            }
        });

	});
	
</script>
@using (Html.BeginForm("LineManagerCompletedActionConfirmation", "Confirmation", FormMethod.Post, new { @id = "mainForm" }))
{
    
    <div class='message'>@Model.Message</div>
    @Html.ValidationSummary(false, @Resources.ERROR_SUMMARY_TITLE, new { id = "validation_errors" })
    
    <div class="full-width clearfix">
        <fieldset class="ui-widget ui-widget-content ui-corner-all TextAlignCentre">
            <legend>@Resources.INCIDENT_LINEMANAGERACTIONSCOMPLETE_CONFIRMATION</legend>
            <div class="full-width clearfix">
                This incident has already been submitted and Line Manager actions are complete.
            </div>
            <div class="full-width clearfix">
                If you need to find out more about the status of this report please contact your Nominated
                Manager (@Model.NominatedManager) (@Model.NominatedManagerEmailAddress) quoting Incident Reference no: @Model.IncidentItem.IncidentID.
            </div>
            <div>
                Please close this window.
            </div>

        </fieldset>
    </div>
}

UcbWeb/Views/Confirmation/LineManagerUpdateConfirmation.cshtml
@model UcbWeb.ViewModels.IncidentVM
@{
    ViewBag.Title = Resources.INCIDENT_CREATION_CONFIRMATION;
}
<script type="text/javascript">
    /// <reference path="jquery-1.7.1.js" />
    /// <reference path="jquery-ui.js" />
    $(document).ready(function () {

        var isDirty = @(Model.IsViewDirty ? Html.Raw("true") : Html.Raw("false"));

        $(':input').change(function () {
            if (!isDirty) {
                isDirty = true;
            }
        });
		
		var $myDialogDelete = $('<div id=\'delete_dialog_fw\'></div>')
        .html('Are you sure you want to delete?<br/>Click OK to confirm.  Click Cancel to stop this action.')
        .dialog({
            autoOpen: false,
            modal: true,
            title: 'Confirmation Required',
            buttons: {
                "OK": function () {
                    $(this).dialog("close");
                    if ($('#IsDeleteConfirmed').val() == "True") {
                        var form = $('#mainForm')
                        var input = $("<input>").attr("type", "hidden").attr("name", "Edit::DeleteSystemParameter").val("");
                        form.append($(input));
                        $('#mainForm')[0].submit();
                        return true;
                    }
                }
                , "Cancel": function () {
                    $(this).dialog("close");
                    return false;
                }
            }

        });
		
		var $myDialogExit = $('<div id=\'exit_dialog_fw\'></div>')
        .html('Are you sure you want to exit?<br/>Click OK to confirm.  Click Cancel to stop this action.')
        .dialog({
            autoOpen: false,
            modal: true,
            title: 'Confirmation Required',
            buttons: {
                "OK": function () {
                    $(this).dialog("close");
                    if ($('#IsExitConfirmed').val() == "True") {
                        var form = $('#mainForm')
                        var input = $("<input>").attr("type", "hidden").attr("name", "Edit::ExitSystemParameter").val("");
                        form.append($(input));
                        $('#mainForm')[0].submit();
                        return true;
                    }
                }
                , "Cancel": function () {
                    $(this).dialog("close");
                    return false;
                }
            }

        });

        $('#mainForm').submit(function (e) {

            if ($('#mainForm').find('input[type="submit"]:focus').attr('name') == 'Edit::DeleteSystemParameter') {
                e.preventDefault();
                $('#IsDeleteConfirmed').val("True");
                var returnValue = $myDialogDelete.dialog('open');  //replace the div id with the id of the button/form
                return returnValue;
            }
            else if ($('#mainForm').find('input[type="submit"]:focus').attr('name') == 'Edit::ExitSystemParameter') {
                if (isDirty == true) {
                    e.preventDefault();
                    $('#IsExitConfirmed').val("True");
                    var returnValue = $myDialogExit.dialog('open');  //replace the div id with the id of the button/form
                    return returnValue;
                }
                else {
                    $('#IsExitConfirmed').val("True");
                    return true;
                }
            }
            else {
                return true;
            }
        });
	});
	
</script>
@using (Html.BeginForm("LineManagerUpdateConfirmation", "Confirmation", FormMethod.Post, new { @id = "mainForm" }))
{
    
    <div class='message'>@Model.Message</div>
    @Html.ValidationSummary(false, @Resources.ERROR_SUMMARY_TITLE, new { id = "validation_errors" })
    
    <div class="full-width clearfix">
        <fieldset class="ui-widget ui-widget-content ui-corner-all TextAlignCentre">
            <legend>@Resources.INCIDENT_LINEMANAGERUPDATE_CONFIRMATION</legend>
            <div class="full-width clearfix">
                The report is being processed by the Unacceptable Customer and Claimant Behaviour Nominated Manager 
                who may contact you for further information.
            </div>
            <div class="full-width clearfix">
                If you need to find out more about the status of this report please contact your Nominated
                Manager (@Model.NominatedManager) (@Model.NominatedManagerEmailAddress) quoting Incident Reference no: @Model.IncidentItem.IncidentID.
            </div>
            <div>
                Please close this window.
            </div>

        </fieldset>
    </div>
}